"""n8n labels: (question, GHSA ID prefix, file under packages/, function).

Each is a function that a fix in an n8n security advisory changed, at
56d336b8 (n8n@2.17.0), before the fixes. Advisories whose fix only adds
a feature, with no flow in one function to judge, are left
out."""
NB = "nodes-base/nodes/"
LC = "@n8n/nodes-langchain/"
CORE = "core/src/"
LABELS = [
 ("sql_injection","mp4j", NB+"SeaTable/v2/actions/row/get.operation.ts","execute"),
 ("sql_injection","mp4j", NB+"SeaTable/v2/actions/row/search.operation.ts","execute"),
 ("sql_injection","hp3c", NB+"Snowflake/Snowflake.node.ts","Snowflake.execute"),
 ("sql_injection","hp3c", NB+"MySql/v1/MySqlV1.node.ts","MySqlV1.execute"),
 ("sql_injection","r6jc", NB+"Oracle/Sql/actions/database/select.operation.ts","execute"),
 ("sql_injection","mhrx", "cli/src/modules/source-control.ee/source-control-import.service.ee.ts","SourceControlImportService.importDataTablesFromWorkFolder"),
 ("sql_injection","jpq7", NB+"MongoDb/GenericFunctions.ts","prepareItems"),
 ("sql_injection","jpq7", NB+"MongoDb/MongoDb.node.ts","MongoDb.execute"),
 ("sql_injection","c37g", NB+"Postgres/v1/genericFunctions.ts","pgInsert"),
 ("sql_injection","c37g", NB+"Postgres/v1/genericFunctions.ts","pgInsertV2"),
 ("sql_injection","c37g", NB+"Postgres/v1/genericFunctions.ts","pgUpdate"),
 ("sql_injection","c37g", NB+"Postgres/v1/genericFunctions.ts","pgUpdateV2"),
 ("sql_injection","jqwr", NB+"Postgres/PostgresTrigger.functions.ts","pgTriggerFunction"),
 ("sql_injection","jqwr", NB+"Postgres/PostgresTrigger.functions.ts","prepareNames"),
 ("sql_injection","jqwr", NB+"Postgres/PostgresTrigger.node.ts","PostgresTrigger.trigger"),
 ("sql_injection","f4f3", NB+"Supabase/GenericFunctions.ts","buildQuery"),
 ("sql_injection","f4f3", NB+"Supabase/GenericFunctions.ts","buildOrQuery"),
 ("sql_injection","f4f3", NB+"Supabase/GenericFunctions.ts","buildGetQuery"),
 ("sql_injection","wxwj", NB+"Elastic/Elasticsearch/Elasticsearch.node.ts","Elasticsearch.execute"),
 ("sql_injection","wxwj", NB+"Google/Firebase/CloudFirestore/GoogleFirebaseCloudFirestore.node.ts","GoogleFirebaseCloudFirestore.execute"),
 ("sql_injection","xrqg", NB+"Supabase/Supabase.node.ts","Supabase.execute"),
 ("sql_injection","4wf3", NB+"Oracle/Sql/actions/database/deleteTable.operation.ts","execute"),
 ("sql_injection","w24g", LC+"utils/helpers.ts","getSessionId"),
 ("sql_injection","w24g", LC+"nodes/memory/MemoryMongoDbChat/MemoryMongoDbChat.node.ts","MemoryMongoDbChat.supplyData"),
 ("sql_injection","5qpp", NB+"Microsoft/Sql/MicrosoftSql.node.ts","MicrosoftSql.execute"),
 ("path_traversal","2vx9", NB+"ExecuteWorkflow/ExecuteWorkflow/GenericFunctions.ts","getWorkflowInfo"),
 ("path_traversal","5xp3", NB+"Git/Git.node.ts","Git.execute"),
 ("path_traversal","xmc9", NB+"EditImage/EditImage.node.ts","EditImage.execute"),
 ("path_traversal","2x35", NB+"EmailSend/v1/EmailSendV1.node.ts","EmailSendV1.execute"),
 ("path_traversal","2x35", NB+"EmailSend/v2/send.operation.ts","execute"),
 ("path_traversal","f2cp", NB+"Elastic/ElasticSecurity/ElasticSecurity.node.ts","ElasticSecurity.execute"),
 ("path_traversal","f2cp", NB+"Elastic/ElasticSecurity/GenericFunctions.ts","getConnector"),
 ("path_traversal","rqch", NB+"Supabase/Supabase.node.ts","Supabase.execute"),
 ("path_traversal","597w", CORE+"execution-engine/node-execution-context/node-execution-context.ts","NodeExecutionContext.getSignedResumeUrl"),
 ("ssrf","3875", CORE+"execution-engine/routing-node.ts","RoutingNode.runNode"),
 ("ssrf","rm2v", NB+"SecurityScorecard/SecurityScorecard.node.ts","SecurityScorecard.execute"),
 ("ssrf","9w78", "cli/src/controllers/dynamic-node-parameters.controller.ts","DynamicNodeParametersController.getOptions"),
 ("ssrf","9w78", "cli/src/services/dynamic-node-parameters.service.ts","DynamicNodeParametersService.getOptionsViaLoadOptions"),
 ("ssrf","2x35", NB+"EmailSend/v2/utils.ts","configureTransport"),
 ("ssrf","vhf8", LC+"nodes/mcp/shared/utils.ts","createAuthFetch"),
 ("ssrf","vhf8", LC+"nodes/mcp/shared/utils.ts","connectMcpClient"),
 ("ssrf","64xh", LC+"nodes/llms/LMOpenAi/LmOpenAi.node.ts","LmOpenAi.supplyData"),
 ("ssrf","64xh", LC+"nodes/llms/LMOpenHuggingFaceInference/LmOpenHuggingFaceInference.node.ts","LmOpenHuggingFaceInference.supplyData"),
 ("ssrf","64xh", LC+"nodes/embeddings/EmbeddingsHuggingFaceInference/EmbeddingsHuggingFaceInference.node.ts","EmbeddingsHuggingFaceInference.supplyData"),
 ("ssrf","64xh", LC+"nodes/tools/ToolHttpRequest/utils.ts","genericCredentialRequest"),
 ("ssrf","jp9j", CORE+"execution-engine/node-execution-context/utils/request-helper-functions.ts","proxyRequestToAxios"),
 ("ssrf","jp9j", CORE+"execution-engine/node-execution-context/utils/request-helper-functions.ts","parseRequestObject"),
 ("ssrf","233r", NB+"EditImage/EditImage.node.ts","EditImage.execute"),
 ("ssrf","c4f6", "cli/src/controllers/oauth/oauth2-credential.controller.ts","OAuth2CredentialController.handleCallback"),
 ("ssrf","9rp2", LC+"nodes/tools/ToolSearXng/ToolSearXng.node.ts","getTool"),
 ("ssrf","95ph", NB+"Google/Gmail/GenericFunctions.ts","encodeEmail"),
 ("xss","h86q", NB+"Facebook/FacebookTrigger.node.ts","FacebookTrigger.webhook"),
 ("xss","h86q", NB+"FacebookLeadAds/FacebookLeadAdsTrigger.node.ts","FacebookLeadAdsTrigger.webhook"),
 ("xss","h86q", NB+"WhatsApp/WhatsAppTrigger.node.ts","WhatsAppTrigger.webhook"),
 ("xss","h86q", NB+"Microsoft/Teams/MicrosoftTeamsTrigger.node.ts","MicrosoftTeamsTrigger.webhook"),
 ("xss","42h7", LC+"nodes/trigger/ChatTrigger/templates.ts","createPage"),
 ("xss","rmr5", NB+"Form/utils/formCompletionUtils.ts","renderFormCompletion"),
 ("xss","x5cw", LC+"nodes/trigger/ChatTrigger/templates.ts","getSanitizedCustomCss"),
 ("command_injection","5xp3", NB+"Git/Git.node.ts","Git.execute"),
]
