package source

import (
	"context"
	"encoding/json"
	"reflect"
	"strings"
	"testing"

	"github.com/deepnoodle-ai/decide/internal/template"
)

// gitDiff covers the kinds of change git reports: a modified file with two
// hunks, an added file, a deleted file, a rename with an edit, a pure
// rename, a binary file, a lockfile, and a generated file.
const gitDiff = `diff --git a/server.go b/server.go
index 1111111..2222222 100644
--- a/server.go
+++ b/server.go
@@ -10,6 +10,7 @@ func (h *Handler) Get(w http.ResponseWriter) {
 	a := 1
 	b := 2
 	c := 3
+	d := 4
 	e := 5
 	f := 6
 	g := 7
@@ -40,4 +41,3 @@ func (h *Handler) Delete(id string) error {
 	if err := check(id); err != nil {
-		return err
-	}
+		return nil
 	return h.db.Delete(id)

diff --git a/new.go b/new.go
new file mode 100644
index 0000000..3333333
--- /dev/null
+++ b/new.go
@@ -0,0 +1,2 @@
+package x
+var y = 1
diff --git a/old.go b/old.go
deleted file mode 100644
index 4444444..0000000
--- a/old.go
+++ /dev/null
@@ -1 +0,0 @@
-package x
diff --git a/a.go b/b.go
similarity index 90%
rename from a.go
rename to b.go
index 5555555..6666666 100644
--- a/a.go
+++ b/b.go
@@ -1,2 +1,2 @@
 package x
-var z = 1
+var z = 2
\ No newline at end of file
diff --git a/same.go b/moved.go
similarity index 100%
rename from same.go
rename to moved.go
diff --git a/logo.png b/logo.png
index 7777777..8888888 100644
Binary files a/logo.png and b/logo.png differ
diff --git a/go.sum b/go.sum
index 9999999..aaaaaaa 100644
--- a/go.sum
+++ b/go.sum
@@ -1 +1,2 @@
 example.com/a v1.0.0 h1:abc=
+example.com/b v1.0.0 h1:def=
diff --git a/api.pb.go b/api.pb.go
index bbbbbbb..ccccccc 100644
--- a/api.pb.go
+++ b/api.pb.go
@@ -1,3 +1,3 @@
 // Code generated by protoc-gen-go. DO NOT EDIT.
 package api
-var v = 1
+var v = 2
`

func diffItems(t *testing.T, stdin string, opts Options) ([]Item, []string) {
	t.Helper()
	tree(t, nil)
	return walk(t, nil, stdin, opts)
}

func diffStates(t *testing.T, items []Item) []diffState {
	t.Helper()
	var out []diffState
	for _, it := range items {
		var s diffState
		if err := json.Unmarshal(it.State, &s); err != nil {
			t.Fatal(err)
		}
		out = append(out, s)
	}
	return out
}

func TestDiffHunks(t *testing.T) {
	items, warnings := diffItems(t, gitDiff, Options{})
	want := []string{"server.go:13", "server.go:42", "new.go:1", "b.go:2"}
	if got := labels(items); !reflect.DeepEqual(got, want) {
		t.Fatalf("labels = %q, want %q", got, want)
	}
	for _, it := range items {
		if it.Unit != template.EachHunk {
			t.Errorf("%s: unit %q", it.Label, it.Unit)
		}
	}
	if string(items[1].Value) != `"func (h *Handler) Delete(id string) error {"` {
		t.Errorf("value = %s, want the hunk's function", items[1].Value)
	}
	states := diffStates(t, items)
	if s := states[1]; s.Path != "server.go" || s.Change != "modified" || s.Lines != "41-43" ||
		!strings.HasPrefix(s.Diff, "@@ -40,4 +41,3 @@") || !strings.Contains(s.Diff, "-\t\treturn err\n") {
		t.Errorf("state = %+v", s)
	}
	if s := states[2]; s.Change != "added" {
		t.Errorf("new.go change = %q", s.Change)
	}
	if s := states[3]; s.Change != "renamed" || s.OldPath != "a.go" || !strings.HasSuffix(s.Diff, `\ No newline at end of file`) {
		t.Errorf("b.go state = %+v", s)
	}
	want = []string{"Skipped old.go (deleted), moved.go (renamed only), logo.png (binary file), and 2 more"}
	if !reflect.DeepEqual(warnings, want) {
		t.Errorf("warnings = %q, want %q", warnings, want)
	}
}

func TestDiffFilesAndLines(t *testing.T) {
	items, _ := diffItems(t, gitDiff, Options{Each: template.EachFile})
	if got, want := labels(items), []string{"server.go", "new.go", "b.go"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("files = %q, want %q", got, want)
	}
	if d := diffStates(t, items)[0].Diff; strings.Count(d, "@@ -") != 2 {
		t.Errorf("a changed file holds every hunk:\n%s", d)
	}

	items, _ = diffItems(t, gitDiff, Options{Each: template.EachLine})
	want := []string{"server.go:13", "server.go:42", "new.go:1", "new.go:2", "b.go:2"}
	if got := labels(items); !reflect.DeepEqual(got, want) {
		t.Fatalf("lines = %q, want %q", got, want)
	}
	if string(items[0].Value) != `"d := 4"` {
		t.Errorf("value = %s", items[0].Value)
	}
}

func TestDiffIncludeAndExclude(t *testing.T) {
	// --include judges a lockfile it names, and leaves out everything else.
	items, _ := diffItems(t, gitDiff, Options{Include: []string{"go.sum"}})
	if got, want := labels(items), []string{"go.sum:2"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("labels = %q, want %q", got, want)
	}
	items, _ = diffItems(t, gitDiff, Options{Exclude: []string{"server.go"}})
	if got, want := labels(items), []string{"new.go:1", "b.go:2"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("labels = %q, want %q", got, want)
	}
}

func TestDiffFormats(t *testing.T) {
	cases := map[string]struct {
		input string
		want  []string
	}{
		"diff -u": {
			"--- old/notes.txt\t2026-10-01 10:00:00\n+++ new/notes.txt\t2026-10-02 10:00:00\n@@ -1,2 +1,2 @@\n hello\n-world\n+there\n",
			[]string{"new/notes.txt:2"},
		},
		"git show": {
			"commit 0123456789abcdef\nAuthor: A <a@b>\n\n    Fix it\n\ndiff --git a/x.go b/x.go\n--- a/x.go\n+++ b/x.go\n@@ -1 +1 @@\n-a\n+b\n",
			[]string{"x.go:1"},
		},
		"format-patch signature": {
			"From 0123456789abcdef Mon Sep 17 00:00:00 2001\nSubject: [PATCH] x\n\n---\n x.go | 2 +-\n\ndiff --git a/x.go b/x.go\n--- a/x.go\n+++ b/x.go\n@@ -1 +1 @@\n-a\n+b\n-- \n2.44.0\n",
			[]string{"x.go:1"},
		},
		"quoted path": {
			"diff --git \"a/my file.go\" \"b/my file.go\"\n--- \"a/my file.go\"\n+++ \"b/my file.go\"\n@@ -1 +1 @@\n-a\n+b\n",
			[]string{"my file.go:1"},
		},
		"blank context line": {
			"diff --git a/x.go b/x.go\n--- a/x.go\n+++ b/x.go\n@@ -1,3 +1,3 @@\n a\n\n-b\n+c\n",
			[]string{"x.go:3"},
		},
	}
	for name, c := range cases {
		t.Run(name, func(t *testing.T) {
			items, _ := diffItems(t, c.input, Options{})
			if got := labels(items); !reflect.DeepEqual(got, c.want) {
				t.Fatalf("labels = %q, want %q", got, c.want)
			}
		})
	}
}

func TestIsDiff(t *testing.T) {
	for _, s := range []string{
		`{"text": "diff --git a/x b/x"}`,
		"From here on, we ship weekly.\n--- \n+++ \n",
		"commit to the plan\nand more text\n",
		"--- not a diff\n+++ either\nno hunk\n",
	} {
		if isDiff([]byte(s)) {
			t.Errorf("isDiff(%q) = true", s)
		}
	}
}

func TestDiffFiles(t *testing.T) {
	tree(t, map[string]string{"change.patch": gitDiff, "notes.txt": "hello\n"})
	items, _ := walk(t, []string{"change.patch"}, "", Options{})
	if len(items) != 4 || items[0].Label != "server.go:13" {
		t.Fatalf("labels = %q", labels(items))
	}
	for _, paths := range [][]string{{"notes.txt"}, nil} {
		err := Walk(context.Background(), paths, strings.NewReader("hello\n"), Options{Each: template.EachHunk}, func(Item) error { return nil })
		if err == nil || !strings.Contains(err.Error(), "is not a diff") {
			t.Errorf("--each hunk on %q: err = %v", paths, err)
		}
	}
	err := Walk(context.Background(), nil, strings.NewReader(gitDiff), Options{Each: template.EachSection}, func(Item) error { return nil })
	if err == nil || !strings.Contains(err.Error(), "use --each hunk, file, or line") {
		t.Errorf("--each section on a diff: err = %v", err)
	}
}

func TestLargeHunkHasParts(t *testing.T) {
	var b strings.Builder
	b.WriteString("diff --git a/big.go b/big.go\n--- a/big.go\n+++ b/big.go\n@@ -1,0 +1,3000 @@\n")
	for range 3000 {
		b.WriteString("+" + strings.Repeat("x", 60) + "\n")
	}
	items, _ := diffItems(t, b.String(), Options{})
	if len(items) != 1 || len(items[0].Parts) < 2 {
		t.Fatalf("got %d items, %d parts", len(items), len(items[0].Parts))
	}
	for _, p := range items[0].Parts {
		if len(p.State) > MaxItemBytes {
			t.Errorf("part of %d bytes", len(p.State))
		}
	}
}

func TestGeneratedMarkersAreComments(t *testing.T) {
	// Code that mentions a marker is judged; a marker comment at the top is not.
	in := "diff --git a/lint.go b/lint.go\n--- a/lint.go\n+++ b/lint.go\n@@ -1 +1,2 @@\n package lint\n" +
		"+const marker = \"// Code generated by x. DO NOT EDIT.\" // @generated\n" +
		"diff --git a/gen.py b/gen.py\n--- a/gen.py\n+++ b/gen.py\n@@ -1,2 +1,2 @@\n # @generated by tool\n-x = 1\n+x = 2\n"
	items, warnings := diffItems(t, in, Options{})
	if got, want := labels(items), []string{"lint.go:2"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("labels = %q, want %q", got, want)
	}
	if want := []string{"Skipped gen.py (generated)"}; !reflect.DeepEqual(warnings, want) {
		t.Errorf("warnings = %q, want %q", warnings, want)
	}
}

func TestPatchesInFolders(t *testing.T) {
	tree(t, map[string]string{"proj/a.go": "package a\n\nfunc A() {}\n", "proj/fix.patch": gitDiff})
	// A patch in a folder is an ordinary file, unless --each hunk asks for diffs.
	items, _ := walk(t, []string{"proj"}, "", Options{Each: template.EachFunction})
	if got, want := labels(items), []string{"proj/a.go#L3"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("functions = %q, want %q", got, want)
	}
	items, _ = walk(t, []string{"proj"}, "", Options{})
	if got, want := labels(items), []string{"proj/a.go", "proj/fix.patch"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("files = %q, want %q", got, want)
	}
	items, _ = walk(t, []string{"proj"}, "", Options{Each: template.EachHunk})
	if len(items) != 4 || items[0].Label != "proj/fix.patch: server.go:13" {
		t.Fatalf("hunks = %q", labels(items))
	}
}

func TestMergeCommits(t *testing.T) {
	merge := "commit 0123456789abcdef\nMerge: a b\n\ndiff --cc f.go\nindex 1,2..3\n--- a/f.go\n+++ b/f.go\n@@@ -1,3 -1,3 +1,4 @@@\n  a\n++d\n"
	tree(t, nil)
	err := Walk(context.Background(), nil, strings.NewReader(merge), Options{}, func(Item) error { return nil })
	if err == nil || !strings.Contains(err.Error(), "combined diff") {
		t.Fatalf("err = %v", err)
	}
	items, warnings := walk(t, nil, merge+gitDiff, Options{})
	if len(items) != 4 || len(warnings) != 2 || warnings[0] != "Skipped 1 combined diff from merge commits" {
		t.Errorf("items = %q, warnings = %q", labels(items), warnings)
	}
}

func TestSeveralCommits(t *testing.T) {
	one := "commit 1111111aaaa\n\n    one\n\ndiff --git a/x.go b/x.go\n--- a/x.go\n+++ b/x.go\n@@ -1 +1 @@\n-a\n+b\n"
	two := "commit 2222222bbbb\n\n    two\n\ndiff --git a/x.go b/x.go\n--- a/x.go\n+++ b/x.go\n@@ -1 +1 @@\n-b\n+c\n"
	items, _ := diffItems(t, one+two, Options{})
	if got, want := labels(items), []string{"x.go@1111111:1", "x.go@2222222:1"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("labels = %q, want %q", got, want)
	}
	if s := diffStates(t, items)[0]; s.Path != "x.go" {
		t.Errorf("the model sees path %q", s.Path)
	}
	items, _ = diffItems(t, one, Options{})
	if got, want := labels(items), []string{"x.go:1"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("one commit: labels = %q, want %q", got, want)
	}
}

func TestShortGitHeaders(t *testing.T) {
	tree(t, nil)
	hunk := "@@ -1 +1 @@\n-a\n+b\n"
	for _, header := range []string{"diff --git a", "diff --git a/x", "diff --git ", "diff --git a/ b/"} {
		// With --- and +++ lines, the paths come from them.
		items, _ := walk(t, nil, header+"\n--- a/x.go\n+++ b/x.go\n"+hunk, Options{})
		if got, want := labels(items), []string{"x.go:1"}; !reflect.DeepEqual(got, want) {
			t.Errorf("%q: labels = %q, want %q", header, got, want)
		}
		// Without them, the diff cannot name the file.
		err := Walk(context.Background(), nil, strings.NewReader("diff --git a/y b/y\n--- a/y\n+++ b/y\n"+hunk+header+"\n"+hunk),
			Options{}, func(Item) error { return nil })
		if err == nil || !strings.Contains(err.Error(), "without the file's name") {
			t.Errorf("%q alone: err = %v", header, err)
		}
	}
}

func TestGeneratedMarkerOnDisk(t *testing.T) {
	// The marker is on line 1 of the file; the change is far below it.
	var b strings.Builder
	b.WriteString("// Code generated by stringer. DO NOT EDIT.\n\npackage p\n")
	for i := 4; i <= 120; i++ {
		b.WriteString("var _ = 1\n")
	}
	tree(t, map[string]string{"kind_string.go": b.String(), "plain.go": b.String()[len("// Code generated by stringer. DO NOT EDIT.\n"):]})
	in := "diff --git a/kind_string.go b/kind_string.go\n--- a/kind_string.go\n+++ b/kind_string.go\n@@ -100 +100 @@\n-var _ = 2\n+var _ = 1\n" +
		"diff --git a/plain.go b/plain.go\n--- a/plain.go\n+++ b/plain.go\n@@ -100 +100 @@\n-var _ = 2\n+var _ = 1\n"
	items, warnings := walk(t, nil, in, Options{})
	if got, want := labels(items), []string{"plain.go:100"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("labels = %q, want %q", got, want)
	}
	if want := []string{"Skipped kind_string.go (generated)"}; !reflect.DeepEqual(warnings, want) {
		t.Errorf("warnings = %q, want %q", warnings, want)
	}
}
